In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_excel(r"C:\Users\sande\Downloads\Rawdata.xlsx")
df

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [4]:
df.shape

(6, 6)

In [5]:
df["Name"]

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [6]:
df_cp=df.copy()
df_cp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [7]:
df_cp["Name"]=df_cp["Name"].str.replace(r"\W","",regex=True)
df_cp["Name"]

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [8]:
df_cp["Domain"]=df_cp["Domain"].str.replace(r"\W","",regex=True)
df_cp["Domain"]

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: object

In [9]:
df_cp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [10]:
df_cp["Age"]=df_cp["Age"].str.replace(r"\W","",regex=True)
df_cp["Age"]

0    34years
1       45yr
2        NaN
3        NaN
4       67yr
5       55yr
Name: Age, dtype: object

In [11]:
df_cp

    Name       Domain      Age   Location   Salary      Exp
0   Mike  Datascience  34years     Mumbai   5^00#0       2+
1  Teddy      Testing     45yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst      NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics      NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67yr        NaN   30000-  5+ year
5    Kim          NLP     55yr      Delhi  6000^$0      10+

In [12]:
df_cp["Age"]=df_cp["Age"].str.extract(r"(\d+)")
df_cp["Age"]

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [13]:
df_cp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [48]:
df_cp["Salary"]

0        5
1       10
2        1
3     2000
4    30000
5     6000
Name: Salary, dtype: int32

In [14]:
df_cp["Salary"]=df_cp["Salary"].str.extract(r"(\d+)")
df_cp["Salary"]

0        5
1       10
2        1
3     2000
4    30000
5     6000
Name: Salary, dtype: object

In [15]:
df_cp

    Name       Domain  Age   Location Salary      Exp
0   Mike  Datascience   34     Mumbai      5       2+
1  Teddy      Testing   45  Bangalore     10       <3
2   Umar  Dataanalyst  NaN        NaN      1   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000      NaN
4  Uttam   Statistics   67        NaN  30000  5+ year
5    Kim          NLP   55      Delhi   6000      10+

In [16]:
df_cp["Exp"]=df_cp["Exp"].str.extract(r"(\d+)")
df_cp["Exp"]

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: object

In [17]:
df_cp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai      5    2
1  Teddy      Testing   45  Bangalore     10    3
2   Umar  Dataanalyst  NaN        NaN      1    4
3   Jane    Analytics  NaN   Hyderbad   2000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi   6000   10

In [18]:
df

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [19]:
df["Age"]=df["Age"].str.extract(r"(\d+)")
df["Age"]

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [20]:
df

     Name          Domain  Age   Location   Salary      Exp
0    Mike   Datascience#$   34     Mumbai   5^00#0       2+
1  Teddy^         Testing   45  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#  NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics  NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67        NaN   30000-  5+ year
5     Kim             NLP   55      Delhi  6000^$0      10+

In [21]:
df_cp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai      5    2
1  Teddy      Testing   45  Bangalore     10    3
2   Umar  Dataanalyst  NaN        NaN      1    4
3   Jane    Analytics  NaN   Hyderbad   2000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi   6000   10

In [22]:
df_cp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [23]:
df_cp["Age"]=df_cp["Age"].fillna(np.mean(pd.to_numeric(df_cp["Age"])))
df_cp["Age"]

0       34
1       45
2    50.25
3    50.25
4       67
5       55
Name: Age, dtype: object

In [24]:
df_cp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai      5    2
1  Teddy      Testing     45  Bangalore     10    3
2   Umar  Dataanalyst  50.25        NaN      1    4
3   Jane    Analytics  50.25   Hyderbad   2000  NaN
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi   6000   10

In [25]:
df_cp["Exp"]=df_cp["Exp"].fillna(np.mean(pd.to_numeric(df_cp["Exp"])))
df_cp["Exp"]

0      2
1      3
2      4
3    4.8
4      5
5     10
Name: Exp, dtype: object

In [26]:
df_cp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai      5    2
1  Teddy      Testing     45  Bangalore     10    3
2   Umar  Dataanalyst  50.25        NaN      1    4
3   Jane    Analytics  50.25   Hyderbad   2000  4.8
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi   6000   10

In [27]:
df_cp["Location"]

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [28]:
df_cp["Location"]=df_cp["Location"].fillna(df_cp["Location"].mode()[0])
df_cp["Location"]

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [29]:
df_cp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai      5    2
1  Teddy      Testing     45  Bangalore     10    3
2   Umar  Dataanalyst  50.25  Bangalore      1    4
3   Jane    Analytics  50.25   Hyderbad   2000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi   6000   10

In [30]:
df_cp["Location"]=df_cp["Location"].astype("category")
df_cp["Salary"]=df_cp["Salary"].astype(int)
df_cp["Age"]=df_cp["Age"].astype(int)
df_cp["Exp"]=df_cp["Exp"].astype(int)
df_cp["Domain"]=df_cp["Domain"].astype("category")
df_cp["Name"]=df_cp["Name"].astype("category")

In [31]:
df_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int32
 3   Location  6 non-null      category
 4   Salary    6 non-null      int32
 5   Exp       6 non-null      int32
dtypes: category(3), int32(3)
memory usage: 866.0 bytes

In [33]:
df_cp

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai       5    2
1  Teddy      Testing   45  Bangalore      10    3
2   Umar  Dataanalyst   50  Bangalore       1    4
3   Jane    Analytics   50   Hyderbad    2000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi    6000   10

In [34]:
df_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int32
 3   Location  6 non-null      category
 4   Salary    6 non-null      int32
 5   Exp       6 non-null      int32
dtypes: category(3), int32(3)
memory usage: 866.0 bytes

In [35]:
df_cp[1:3]

    Name       Domain  Age   Location  Salary  Exp
1  Teddy      Testing   45  Bangalore      10    3
2   Umar  Dataanalyst   50  Bangalore       1    4

In [36]:
df_cp[::2]

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai       5    2
2   Umar  Dataanalyst   50  Bangalore       1    4
4  Uttam   Statistics   67  Bangalore   30000    5

In [37]:
df_cp[2::2]

    Name       Domain  Age   Location  Salary  Exp
2   Umar  Dataanalyst   50  Bangalore       1    4
4  Uttam   Statistics   67  Bangalore   30000    5

In [38]:
x_iv=df_cp[["Name","Domain","Age","Location","Exp"]]
x_iv

    Name       Domain  Age   Location  Exp
0   Mike  Datascience   34     Mumbai    2
1  Teddy      Testing   45  Bangalore    3
2   Umar  Dataanalyst   50  Bangalore    4
3   Jane    Analytics   50   Hyderbad    4
4  Uttam   Statistics   67  Bangalore    5
5    Kim          NLP   55      Delhi   10

In [39]:
y_dv=df_cp[["Salary"]]
y_dv

   Salary
0       5
1      10
2       1
3    2000
4   30000
5    6000

In [40]:
imp=pd.get_dummies(df_cp)
imp

,Age,Salary,Exp,Name_Jane,Name_Kim,Name_Mike,Name_Teddy,Name_Umar,Name_Uttam,Domain_Analytics,Domain_Dataanalyst,Domain_Datascience,Domain_NLP,Domain_Statistics,Domain_Testing,Location_Bangalore,Location_Delhi,Location_Hyderbad,Location_Mumbai
0,34,5,2,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,True
1,45,10,3,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
2,50,1,4,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False
3,50,2000,4,True,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False
4,67,30000,5,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False
5,55,6000,10,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,False

In [41]:
import seaborn as sns

In [46]:
sns.lineplot(x="Age",y="S"data=df_cp)
df_cp

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai       5    2
1  Teddy      Testing   45  Bangalore      10    3
2   Umar  Dataanalyst   50  Bangalore       1    4
3   Jane    Analytics   50   Hyderbad    2000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi    6000   10

In [47]:
df

     Name          Domain  Age   Location   Salary      Exp
0    Mike   Datascience#$   34     Mumbai   5^00#0       2+
1  Teddy^         Testing   45  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#  NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics  NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67        NaN   30000-  5+ year
5     Kim             NLP   55      Delhi  6000^$0      10+

In [49]:
df["Salary"]

0     5^00#0
1    10%%000
2    1$5%000
3     2000^0
4     30000-
5    6000^$0
Name: Salary, dtype: object

In [52]:
df

     Name          Domain  Age   Location Salary      Exp
0    Mike   Datascience#$   34     Mumbai      5       2+
1  Teddy^         Testing   45  Bangalore     10       <3
2   Uma#r  Dataanalyst^^#  NaN        NaN      1   4> yrs
3    Jane     Ana^^lytics  NaN   Hyderbad   2000      NaN
4  Uttam*      Statistics   67        NaN  30000  5+ year
5     Kim             NLP   55      Delhi   6000      10+

In [69]:
emp1=pd.read_excel(r"C:\Users\sande\Downloads\Rawdata.xlsx")
emp1

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [54]:
emp1["Salary"]

0     5^00#0
1    10%%000
2    1$5%000
3     2000^0
4     30000-
5    6000^$0
Name: Salary, dtype: object

In [76]:
emp1["Salary"].str.replace(r"(\W)","",regex=True)

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: object

In [77]:
emp1["Exp"]

0         2+
1         <3
2     4> yrs
3        NaN
4    5+ year
5        10+
Name: Exp, dtype: object

In [84]:
emp1["Exp"].str.extract(r"(\d+)")

     0
0    2
1    3
2    4
3  NaN
4    5
5   10