# Day-46(8July)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

salarydf=pd.read_csv(r"C:\Users\sande\Downloads\Salary_Data.csv")

In [4]:
salarydf.mean()

YearsExperience        5.313333
Salary             76003.000000
dtype: float64

In [5]:
salarydf["Salary"].mean()

76003.0

In [6]:
salarydf.median()

YearsExperience        4.7
Salary             65237.0
dtype: float64

In [7]:
salarydf["Salary"].median()

65237.0

In [8]:
salarydf["Salary"].mode()[0]

37731

In [9]:
# variance
salarydf.var()

YearsExperience    8.053609e+00
Salary             7.515510e+08
dtype: float64

In [10]:
# Standard Deviation
salarydf["Salary"].std()

27414.4297845823

In [11]:
# Coefficient of Variation
from scipy.stats import variation
variation(salarydf.values)

array([0.5251297 , 0.35463929])

In [12]:
variation(salarydf["Salary"])

0.3546392938275572

In [13]:
# correlation
salarydf.corr()

                 YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [14]:
salarydf["Salary"].corr(salarydf["YearsExperience"])

0.9782416184887598

In [15]:
# skewness
salarydf.skew()

YearsExperience    0.37956
Salary             0.35412
dtype: float64

In [16]:
salarydf["Salary"].skew()

0.35411967922959153

In [17]:
#Standard Error
salarydf.sem()

YearsExperience       0.518125
Salary             5005.167198
dtype: float64

In [18]:
salarydf["Salary"].sem()

5005.167198052405

In [19]:
# Z-score
import scipy.stats as stats
salarydf.apply(stats.zscore)

    YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [20]:
stats.zscore(salarydf["Salary"])

0    -1.360113
1    -1.105527
2    -1.419919
3    -1.204957
4    -1.339781
5    -0.718307
6    -0.588158
7    -0.799817
8    -0.428810
9    -0.698013
10   -0.474333
11   -0.749769
12   -0.706620
13   -0.702020
14   -0.552504
15   -0.299217
16   -0.370043
17    0.262859
18    0.198860
19    0.665476
20    0.583780
21    0.826233
22    0.938611
23    1.402741
24    1.240203
25    1.097402
26    1.519868
27    1.359074
28    1.721028
29    1.701773
Name: Salary, dtype: float64

In [21]:
# Degree of Freedom
a= salarydf.shape[0]
b= salarydf.shape[1]
degree_of_freedom = a-b
print("a is ",a)
print("b is ",b)
print("Degree of Freedom is ",degree_of_freedom)

a is  30
b is  2
Degree of Freedom is  28